# Generated by Django 5.0.6 on 2024-07-10 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truckBot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapedHistory',
        ),
    ]
