# Generated by Django 5.0.6 on 2024-07-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckBot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posting_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
