# Generated by Django 5.0.5 on 2024-05-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckBot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zoom_exe_path',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='zoom_phone_numb',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
