# Generated by Django 5.0.6 on 2024-07-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckBot', '0002_delete_scrapedhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='headless',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='timedelta',
            field=models.IntegerField(default=0),
        ),
    ]
