# Generated by Django 5.0.6 on 2024-07-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckBot', '0002_user_posting_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='insolent',
            field=models.BooleanField(default=False),
        ),
    ]
