# Generated by Django 5.0.5 on 2024-05-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckBot', '0003_load_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='landstar_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='landstar_username',
        ),
        migrations.AddField(
            model_name='user',
            name='landstar_credentials_path',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
