# Generated by Django 5.0.6 on 2024-07-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truckBot', '0003_user_insolent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='insolent',
            new_name='banned',
        ),
    ]
