# Generated by Django 5.0.6 on 2024-07-03 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckBot', '0004_rename_insolent_user_banned'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaneLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('pickup', models.CharField(max_length=30)),
                ('delivery', models.CharField(max_length=30)),
                ('miles', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('equipment', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lane_loads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('origin', 'destination', 'pickup', 'delivery', 'weight', 'price')},
            },
        ),
    ]
