# Generated by Django 5.0.6 on 2024-07-04 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truckBot', '0005_laneload'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='laneload',
            unique_together={('origin', 'destination', 'pickup', 'delivery', 'miles', 'weight')},
        ),
    ]
