# Generated by Django 5.0.6 on 2024-07-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckBot', '0006_alter_laneload_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='laneload',
            name='posted',
            field=models.BooleanField(default=False),
        ),
    ]
